export const authAppearance = {
  variables: {
    colorPrimary: "var(--auth-clerk-primary)",
    colorText: "var(--auth-clerk-text)",
    colorTextSecondary: "var(--auth-clerk-text-secondary)",
    colorBackground: "transparent",
    colorInputBackground: "var(--auth-clerk-input-bg)",
    colorInputText: "var(--auth-clerk-input-text)",
    colorDanger: "var(--auth-clerk-danger-text)",
    borderRadius: "1.35rem",
    fontFamily: "var(--font-geist-sans)",
  },
  elements: {
    rootBox: [
      "w-full",
      "motion-safe:animate-[auth-fade-up_0.75s_cubic-bezier(0.16,1,0.3,1)_both]",
    ].join(" "),
    cardBox: "w-full max-w-[440px] shadow-none",
    card: [
      "w-full rounded-[20px] border border-[var(--auth-clerk-card-border)]",
      "bg-[linear-gradient(180deg,var(--auth-clerk-card-bg-start),var(--auth-clerk-card-bg-end))]",
      "px-6 py-6 shadow-[0_24px_60px_rgba(0,0,0,0.18)] backdrop-blur-2xl transition-all duration-300 sm:px-8 sm:py-8",
    ].join(" "),
    headerTitle: "text-3xl font-semibold tracking-tight text-[var(--auth-clerk-text)]",
    headerSubtitle: "mt-2 text-sm leading-6 text-[var(--auth-clerk-text-secondary)]",
    socialButtonsBlockButton: [
      "h-12 rounded-2xl border border-[var(--auth-clerk-social-border,var(--auth-clerk-input-border))] bg-[var(--auth-clerk-social-bg,var(--auth-clerk-input-bg))] text-[var(--auth-clerk-text)] shadow-none",
      "transition-all duration-300 hover:-translate-y-0.5 hover:brightness-[1.03] hover:border-[var(--auth-clerk-primary)] hover:bg-[var(--auth-clerk-social-bg-hover,var(--auth-clerk-input-bg-focus))] hover:text-[var(--auth-clerk-text)] hover:shadow-[0_18px_40px_rgba(0,0,0,0.18)]",
    ].join(" "),
    socialButtonsBlockButtonText: "text-sm font-medium text-[var(--auth-clerk-text)]",
    dividerLine: "bg-[var(--auth-clerk-input-border)]",
    dividerText: "text-xs font-medium uppercase tracking-[0.22em] text-[var(--auth-clerk-text-secondary)]",
    formFieldLabel: "text-sm font-medium text-[var(--auth-clerk-text)]",
    formFieldInput: [
      "h-12 rounded-2xl border border-[var(--auth-clerk-input-border)] bg-[var(--auth-clerk-input-bg)] text-[var(--auth-clerk-input-text)] shadow-none",
      "placeholder:text-[var(--auth-clerk-placeholder)] transition-all duration-300",
      "focus:border-[#3b82f6] focus:bg-[var(--auth-clerk-input-bg-focus)] focus:shadow-[0_0_0_4px_rgba(59,130,246,0.22)] focus:ring-0",
    ].join(" "),
    formButtonPrimary: [
      "h-12 w-full rounded-2xl border border-blue-400/20 bg-[#3b82f6]",
      "text-sm font-semibold text-white shadow-[0_18px_40px_rgba(0,0,0,0.28)] transition-all duration-300",
      "hover:-translate-y-0.5 hover:bg-[#2563eb] hover:brightness-[1.02] hover:shadow-[0_24px_52px_rgba(0,0,0,0.34)] active:translate-y-0 active:scale-[0.99]",
    ].join(" "),
    footerActionText: "text-sm text-[var(--auth-clerk-text-secondary)]",
    footerActionLink: "font-medium text-[var(--auth-clerk-link)] transition hover:text-[var(--auth-clerk-link-hover)]",
    formFieldAction: "text-[var(--auth-clerk-link)] transition hover:text-[var(--auth-clerk-link-hover)]",
    identityPreviewText: "text-sm text-[var(--auth-clerk-text)]",
    identityPreviewEditButton: "text-[var(--auth-clerk-link)] transition hover:text-[var(--auth-clerk-link-hover)]",
    formResendCodeLink: "text-[var(--auth-clerk-link)] transition hover:text-[var(--auth-clerk-link-hover)]",
    otpCodeFieldInput: [
      "h-12 rounded-2xl border border-[var(--auth-clerk-input-border)] bg-[var(--auth-clerk-input-bg)] text-[var(--auth-clerk-input-text)] shadow-none",
      "transition-all duration-300 focus:border-[#3b82f6] focus:bg-[var(--auth-clerk-input-bg-focus)] focus:shadow-[0_0_0_4px_rgba(59,130,246,0.18)] focus:ring-0",
    ].join(" "),
    alertText: "text-sm font-medium",
    alertClerkError: "rounded-2xl border border-[var(--auth-clerk-danger-border)] bg-[var(--auth-clerk-danger-bg)] text-[var(--auth-clerk-danger-text)]",
    formFieldSuccessText: "text-[var(--auth-clerk-success)]",
    formFieldErrorText: "text-[var(--auth-clerk-danger-text)]",
    formFieldHintText: "text-[var(--auth-clerk-text-secondary)]",
    formFieldInputShowPasswordButton: "text-[var(--auth-clerk-text-secondary)] transition hover:text-[var(--auth-clerk-text)]",
    footer: "pt-5",
    footerAction: "pt-2",
    navbar: "hidden",
    modalBackdrop: "bg-slate-950/80 backdrop-blur-sm",
  },
} as const;
